name: omarchy-hyperfy
services:
  hyperfy:
    image: ghcr.io/hyperfy-xyz/hyperfy:dev
    container_name: ${HYPERFY_CONTAINER_NAME:-hyperfy-web}
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    env_file:
      - ${HOST_REPO_DIR}/.env
    ports:
      - "${HYPERFY_PORT}:3000"
    volumes:
      - hyperfy_data:/app/world
volumes:
  hyperfy_data:
