name: omarchy-hyperfy
services:
  hyperfy:
    image: ${HYPERFY_NODE_IMAGE:-node:22.11-alpine}
    container_name: ${HYPERFY_CONTAINER_NAME:-hyperfy-web}
    restart: unless-stopped
    working_dir: /app
    environment:
      - NODE_ENV=development
      - PORT=${HYPERFY_PORT}
    ports:
      - "${HYPERFY_PORT}:${HYPERFY_PORT}"
    volumes:
      - ${HOST_REPO_DIR}:/app
      - hyperfy_node_modules:/app/node_modules
      - hyperfy_npm_cache:/root/.npm
    command: >
      sh -lc "
      echo 'Node:' $(node -v);
      if [ ! -d node_modules ]; then npm ci || npm install; fi;
      if [ -f package.json ]; then
        npm start;
      else
        echo 'No package.json found';
        exit 1;
      fi
      "
volumes:
  hyperfy_node_modules:
  hyperfy_npm_cache: