version: 1

# Rendering method
# NVIDIA: try "dmabuf" first, use "software" if corruption
# AMD RDNA3: use "software"
blit_method: "software"

run_compositor_at_start: false
auto_hide: true
auto_hide_delay: 750
keyboard_repeat_delay: 200
keyboard_repeat_rate: 50

# Dashboard (optional)
dashboard:
  exec: "wayvr-dashboard"
  args: ""
  env: []

# Display configuration - Optimized for VR comfort
displays:
  # Small utility display on right hand
  watch:
    width: 400
    height: 500
    scale: 1.2
    attach_to: "HandRight"
    pos: [0.0, 0.0, 0.15]
    rotation: {axis: [1.0, 0.0, 0.0], angle: -30.0}
  
  # Main workspace display
  main:
    width: 1600
    height: 900
    scale: 1.1
    primary: true
  
  # Secondary display for media/browsing
  secondary:
    width: 1920
    height: 1080
    scale: 1.0

# Application catalog - Clean, minimal VR setup
catalogs:
  default_catalog:
    apps:
      # Essential system tools
      - name: "Terminal"
        target_display: "main"
        exec: "alacritty"
        env: ["WAYLAND_DISPLAY=wayland-20", "DISPLAY="]
        shown_at_start: false

      - name: "System Monitor"
        target_display: "watch"
        exec: "alacritty"
        args: "-e btop"
        env: ["WAYLAND_DISPLAY=wayland-20", "DISPLAY="]

      # Core productivity apps (VR-friendly)
      - name: "Browser"
        target_display: "secondary"
        exec: "firefox"
        args: "--new-window"
        env: ["MOZ_ENABLE_WAYLAND=1", "DISPLAY="]

      - name: "File Manager"
        target_display: "main"
        exec: "nautilus"
        env: ["DISPLAY="]

      - name: "Text Editor"
        target_display: "main"
        exec: "typora"
        env: ["DISPLAY="]

      # Media and communication
      - name: "Music"
        target_display: "secondary"
        exec: "spotify"
        args: "--enable-features=UseOzonePlatform --ozone-platform=wayland"
        env: ["DISPLAY="]

      - name: "Notes"
        target_display: "main"
        exec: "obsidian"
        args: "--enable-features=UseOzonePlatform --ozone-platform=wayland"
        env: ["DISPLAY="]
